### ISSUE TITLE
Can't find JWT - Payload

### ISSUE THREAD

**Issue by SmokeyTux** [TomFahey/nginx-cloudflare-jwt-checker#1]
Hi,

Is there a way to view the payload and extract email or something like that?

Also get same error over and over: "failed to find a jwt"
If I map the cookie as a variable there is definitely a cloudflare jwt present.

Thank you!

**Comment by TomFahey** [comment]
Hi, sorry for the late reply, I hope this is still helpful.

In terms of extracting email, from what I can remember, you can choose the particular claim that you want to verify using the `jwt_cf_claim_key` nginx directive, as mentioned in the README. So, presumably, you would choose "email", instead of "AUD", depending on the exact structure of the JWT you're expecting and specify the value required to authenticate with the `jwt_cf_claim_value` directive.

In terms of the error you're getting, have you filled in all the correct information for the other nginx directives, such as the `jwt_cf_cert_url`? Could you post the relevant part of your .conf file?

**Comment by SmokeyTux** [comment]
Hi,

Thanks to get back to me.
Is it ok for you if I send error log and nginx.conf in private?
Don't have the time to redact things. Solution of mishap can still be posted later?

Thanks

**Comment by TomFahey** [comment]
Yeah, go ahead and I'll take a look. You can reach me at tomp.fahey@gmail.com

**Comment by TomFahey** [comment]
@MaartenMees

Ok, I think the problem may have been with the example directive I gave in the README.md; the quotation marks around "CF_Authorization" shouldn't be there, as they cause the cookie key to be incorrectly parsed. I've updated the README.md ( https://github.com/TomFahey/nginx-cloudflare-jwt-checker/commit/0fee56659daed5635e6704b2ba624b283464359c ) as such, the correct directive should look like:

`jwt_cf_validation_type COOKIE=CF_Authorization;` 

Maybe try this and see where you get?

**Comment by SmokeyTux** [comment]
Hi,

Thanks for the time you are putting in this!
Unfortunaly I don't have the time to try it right away. Maybe later this week, but it's crazy at work because of corona. But deffenitly will try it!

Kind regards,

Maarten Mees

(btw, sorry for the very bad english, stupid spell check isn't working 🙂)
________________________________
Van: TomFahey <notifications@github.com>
Verzonden: woensdag 27 januari 2021 19:33
Aan: TomFahey/nginx-cloudflare-jwt-checker <nginx-cloudflare-jwt-checker@noreply.github.com>
CC: Maarten Mees <maartenmees@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [TomFahey/nginx-cloudflare-jwt-checker] Can't find JWT - Payload (#1)


Ok, I think the problem may have been with the example directive I gave; the quotation marks around "CF_Authorization" shouldn't be there, as they cause the cookie key to be incorrectly parsed. I've updated the README.md ( 0fee566<https://github.com/TomFahey/nginx-cloudflare-jwt-checker/commit/0fee56659daed5635e6704b2ba624b283464359c> ) as such, the correct directive should look like:
jwt_cf_validation_type COOKIE=CF_Authorization;

Maybe try this and see where you get?

**Comment by TomFahey** [comment]
No problem whatsoever - I'm grateful that you should highlight this, as I totally would have missed it otherwise!

Also your english is fine, seems fluent in fact.
